# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 474608d460b8fe37916842c4e767cd2f080d8d455142c2677fe4f9d0a193acaa6634091f3900e7f602444895a14f5d3c4693edd58f47d0afdba01e92e24c3165

test:
  secret_key_base: 0761279da4528fd7fa7f51ad35507ce7ca8529d566b90eda39c00e766abf5121c64543fb50d9630be848eea4dc3458c5c0c99667ccd3dbd60dad5d046b86fe76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
